### ISSUE TITLE
Constant crazy network upload

### ISSUE THREAD

**Issue by no112358** [rule110-io/surge#42] opened 2020-12-17 01:20 UTC
**Describe the bug**
While Surge shows no file transfers active, all of them are at 0 bytes / s, if I look at the task manager, Surge is constantly uploading at 30mbit (max of my bandwidth).
[surge_bug 30mbit upload.log](https://github.com/rule110-io/surge/files/5706388/surge_bug.30mbit.upload.log)

I had 20 clients connected, and could see about 50 "remote files" being offered. I restarted Surge and now it's kinda weird, 6 clients connected and I can't see any "Remote Files" but one. NO MORE crazy uploading this time. At least not yet.
[surge restart can't see remote files.log](https://github.com/rule110-io/surge/files/5706390/surge.restart.can.t.see.remote.files.log)

After another restart, Surge found the remote files and is running 5 connected clients and no crazy upload. But I can't see all the remote files I saw when I had the max upload bug at the start. I only see 20 files being shared.
[surge another restart I can see files.log](https://github.com/rule110-io/surge/files/5706396/surge.another.restart.I.can.see.files.log)

**Expected behavior**
It's not supposed saturate my whole bandwidth, while IDLE.

**Desktop (please complete the following information):**
 - Windows 10 2020h
 - Firefox
 - Surge 0.2.1 beta

**Comment by no112358** [comment] 2020-12-17 15:07
Here we go again, lower consumption but still

[surge again.log](https://github.com/rule110-io/surge/files/5710259/surge.again.log)


![surge again](https://user-images.githubusercontent.com/75950250/102505099-e4e36a00-4081-11eb-9fe4-122a847fee85.png)

**Comment by MutsiMutsi** [comment] 2020-12-17 16:10
Hi thanks for reporting!

For the record, do you have any files that have been uploading or download recently that couldve been the cause? Can you verify if this bandwidth is upload or download?

If all fails could you wipe %appdata%/surge/db and see if that resolves your issues.
This has not yet been reported by other win clients and we have not come across this yet think.


Btw with regards to incrementing files/client count we will address that in 0.2.2-beta, we have identified the cause.

**Comment by no112358** [comment] 2020-12-17 17:48
No current uploads or downloads. Also at the bottom of your app theres a bandwidth meter it all says 0 bytes/s. I can only see this BW in the task manager.

I'll wipe db and report if I see this again.

EDIT:
I wiped it, and added back the downloads I had (since all was reset) and I noticed Surge redownloads everything from scratch instead of using the data already on the disk. This should also be fixed.

EDIT 2:
found another bug. I wanted to add a .zip file to Surge, I can't do it. When you select the zip file and click "open", it just opens up / goes inside the zip file and I can't add the actual whole zip file...

EDIT 3:
I can't download anything from Surge network now. The downloads don't start or get stuck despite there being seeds available. Also the downloads that are stuck at 0 or whatever % say Remaining "a few seconds"... lol

EDIT 4:
7 hours later the most basic thing I wanted to download surge-0.2.1-beta.macOS.zip still hasn't even started downloading, with supposedly 3 seeds available. Stuck at 0 %. I tried restarting Surge and now all the macOS files of Surge aren't there.

EDIT 5:
I dunno what's going on.. nothing is working anymore after the db delete. Can't download, can't even find the surge beta files on the network. I'll try a complete wipe even the account.

EDIT 6:
I uninstalled Surge and deleted all the folders associated with it and tried again. I started Surge and added a few downloads and uploads (still can't add zip files) to see if started working and Surge crashed without warning.
[surge.log](https://github.com/rule110-io/surge/files/5713110/surge.log)

EDIT 7:
Still can't download the surge beta files from the network. Stuck at 0% some others did finish though.
Can't upload the log file, github says "we dont' support that file type" lol

**Comment by MutsiMutsi** [comment] 2020-12-18 09:42
Good morning @no112358 

Valueable feedback as always, I'll write my responses below your remarks.

------

> I wiped it, and added back the downloads I had (since all was reset) and I noticed Surge redownloads everything from scratch instead of using the data already on the disk. This should also be fixed.

**We dont identify this as a bug, we track chunk progress in the db files, wiping that wipes our track record of the files that are in surge, if you mean we should do a local file scanning on a per chunk akin to file integrity that would be a nice feature request for in the future, we are in very early beta stages still :). That said this tells me you did have downloads/uploads potentionally going. Perhaps it was just the bandwidth indicator in surge that wasnt correctly displaying for a file, but in reality you were downloading/uploading which would explain the bandwidth usage?**

> found another bug. I wanted to add a .zip file to Surge, I can't do it. When you select the zip file and click "open", it just opens up / goes inside the zip file and I can't add the actual whole zip file...

**We too identified this issue to be with the open file dialog, we have changed this to another implementation in the next release**

> Replies to edit 3 / 4 / 5 / 7

**This behaviour has been replicated from long running surge clients, our peer/file discovery implementation has to scan through the network from peer2peer. However we have identified an issue where files/clients were still marked as online (nPubSub subscription expired before shutdown of remote client to be specific). This explains files listed/clients online which are no longer actually there as you have found from restarting the client. There are very little clients always on at this stage leaving yours on for a long duration, with this bug in place will lead to these issues. We will work on resolving this for the next release**

> I uninstalled Surge and deleted all the folders associated with it and tried again. I started Surge and added a few downloads and uploads (still can't add zip files) to see if started working and Surge crashed without warning.

**Would you also have a panic file for this, next to the log file? %appdata%/surge/ the normal logs dont catch fatal errors**

**Comment by no112358** [comment] 2020-12-18 15:00
Left surge running, the downloads of beta surge files are still stuck at 0%.

There's no panic file, theres just the db folder, account.surge and surge.log

I canceled the files, and tried adding them again. When I clicked the add button to start the downloads, nothing happened. I was like heh? While I was writing this they appeared and actually downloaded themselves.

I haven't caught the idle uploads this time. I am sure that all the shared files were at 0 bytes/s when the 30 mbit upload happened. It also went on for many hours, so I doubt any share would keep that BW up for that long. Will keep on watching. Do you suggest any program to see what exactly is going on when it spikes up again?

**Comment by MutsiMutsi** [comment] 2020-12-18 15:25
I appreciate your persistence!
Its all very hit and miss with these issues it seems, from the way you describe it.

If you want to check out the up vs download bandwidth you can use the windows resource monitor (run resmon.exe) there you should be able to see more indepth info :)

**Comment by no112358** [comment] 2020-12-18 20:00
> 
> 
> I appreciate your persistence!
> Its all very hit and miss with these issues it seems, from the way you describe it.
> 
> If you want to check out the up vs download bandwidth you can use the windows resource monitor (run resmon.exe) there you should be able to see more indepth info :)

Ok I'll do that. No crazy BW increase for the last 4 hours, so I'll just check it tomorrow.

Tried repackaging the zip file to 7z (7zip file) and it allows upload. It's just a zip thing.

Ohh and BTW good job on async adding of uploads, looks great :D

**Comment by no112358** [comment] 2020-12-19 14:38
Nothing new on the bandwidth part, i'll try adding as many downloads as possible, to see if that changes it.

I do have a question, does Surge preallocate disk space? There was unusually high disk usage when I added a big download.

I noticed a repeating problem, when clicking on the download button, nothing happens, and then after a minute or two the file adds itself to the download. In fact any file I want to download, doesn't add to the downloads. This should be instant of course.

EDIT: I keep comming back and Surge is not running, seems like it's crashing or I'm dumb enough to keep pressing X to minimize it. There's no panic logs anywhere in surges appdata. Would be nice if Surge asked the user if they want to minimize or close the program upon clicking X :D

EDIT 2:
I literally just caught Surge doing the bandwidth thing and I wanted to take a screenshot and Surge crashed before my eyes. No panic log. I restarted it and it did it for some time, up to 10mbit, I presume it was discovering network etc and then it stopped.

![surge](https://user-images.githubusercontent.com/75950250/102703158-a5787180-426b-11eb-94dd-b26ff60f1cb4.png)

**Comment by MutsiMutsi** [comment] 2020-12-20 02:16
Indeed it does preallocate the entire file as length is known, this allows for high concurrency chunk writing to that file without having to lock and also guarantees the file will fit before attempting to download. 

Downloads should indeed start right away I think this might be tied to the other issues and instability you have been experiencing. With regards to minimizing to tray that could potentionally come with wails framework v2 (https://github.com/wailsapp/wails/issues/514#issuecomment-716377493)

Most issues seem to be linked to connected clients accumulating with offline clients, and file listings. These are addressed in the upcoming 0.2.2-beta version. 

Lastly the high bandwidth somewhere floating between 5-10mbit was also experienced by be today, all of it was download traffic but no surge related traffic nor disk usage was present. I will further escalate this to try to get to the bottom of this. That said it has disappeard for me since a few  hours ago. Additionally removing my account file and generating a new one on startup also fixed that incoming bandwidth, but so far its inconclusive.

**Comment by no112358** [comment] 2020-12-20 03:06
Any ETA on the 0.2.2 beta?
Also is there a changelog somewhere I can see what was fixed / added?

EDIT:
GOT IT!! Nothing downloading or uploading, if you believe Surge and it's stats. But Windows says theres a 30 mbit upload.
![surge](https://user-images.githubusercontent.com/75950250/102704238-0f4b4800-4279-11eb-8c9d-bd098d481da7.png)

**Comment by MutsiMutsi** [comment] 2020-12-21 13:10
No real ETA but we've been pretty rapid with rolling out fixes, issues/roadmap and changelogs can be tracked on github and the website https://surge.rule110.io/

What's interesting is that your bandwidth is all upload, whereas mine was all download. Are you running this client always on? We're definitely still investigating this issue.

**Comment by no112358** [comment] 2020-12-21 14:05
> No real ETA but we've been pretty rapid with rolling out fixes, issues/roadmap and changelogs can be tracked on github and the website https://surge.rule110.io/
> 
> What's interesting is that your bandwidth is all upload, whereas mine was all download. Are you running this client always on? We're definitely still investigating this issue.

It starts doing the upload thing usually after some time passes, usually a day or so. It was always upload in my case, never download. I leave the client running until the upload starts, then I restart, because I need the bandwidth for other stuff.

**Comment by no112358** [comment] 2020-12-21 19:05
Been testing out on my laptop also, and I've noticed some weird "downloads" or whatever, long after the file has been downloaded. I mean, I get that the network has overhead traffic, but it seems kinda a lot to me, not sure how to feel about it. The traffic comes and goes randomly, so I take it that's overhead?

![surgetraffic](https://user-images.githubusercontent.com/75950250/102812673-b6d69080-43c7-11eb-88d2-ad84b2541f05.png)

Also if someone clicks the download button in the "remote files" tab, like a mad person, because the download doesn't start immediately (bug), there will be the same amount of notifications after the file downloads successfully. I was such a mad person today and got around 20 notifications :D

**Comment by resu12** [comment] 2020-12-22 07:09
I noticed the upload too (only upload, no download) when Surge is running for longer time (Windows 10). It stops after Surge restart.

![Screenshot 2020-12-22 080147](https://user-images.githubusercontent.com/43032714/102859650-9391fc80-442c-11eb-8588-adffbd35d705.png)

**Comment by no112358** [comment] 2020-12-26 05:16
I'm 100% the bug starts, when the client connects to a certain number of clients on the network. It was fine when under 10 clients, but woke up this morning at 16 clients and there was a 30mbit upload again.

**Comment by MutsiMutsi** [comment] 2020-12-26 10:32
Im fairly confident our large refactoring and architectural improvements will resolve this, however this has not been tested at larger scales yet, so please sit tight for 0.2.2 / 0.3 :)

**Comment by MutsiMutsi** [comment] 2021-01-05 10:49
@no112358 when you have the time could you kindly confirm this has been resolved for you in v0.3.0, if not we will reopen the issue.

**Closed as completed by MutsiMutsi** 2021-01-05 10:49 UTC
